[build]
  publish = "."

# 确保正确识别 HTML 文件
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 设置 headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"